name: CD

on:
  push:
      branches: [ main ]

jobs:
    deploy:
          runs-on: ubuntu-latest
          steps:
              -   name: Deploy to production
                  uses: appleboy/ssh-action@v1.0.3
                  with:
                      host: ${{ secrets.SSH_HOST }}
                      username: ${{ secrets.SSH_USERNAME }}
                      password: ${{ secrets.SSH_PASSWORD }}
                      port: 22
                      script: ${{ secrets.SCRIPT_CMD }}

